//
// Copyright (c) AIT Austrian Institute of Technology GmbH.
// Distributed under the terms of the Modified BSD License.
//

package at.ac.ait.lablink.core.encoding.protobuf;

import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;

/**
 * Class LlJoinLeaveMessage.
 *
 * <p>This file has been generated by the protocol buffer compiler. It has 
 * been slightly modified to comply with (most of) the style checker rules 
 * and generate valid Javadoc output.
 *
 * <p>Only edit this file if you really know what you are doing!!!
 */
@SuppressWarnings("deprecation")
public final class LlJoinLeaveMessage {

  /**
   * Instantiates a new Lablink sync message data item.
   */
  private LlJoinLeaveMessage() {}

  /**
   * Register all extensions.
   *
   * @param registry the registry
   */
  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  /**
   * Register all extensions.
   *
   * @param registry the registry
   */
  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  /**
   * The Interface JoinLeaveMessageOrBuilder.
   */
  public interface JoinLeaveMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JoinLeaveMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The client Id
     * </pre>
     *
     * <code>fixed64 runtimeClientId = 1;</code>.
     *
     * @return the runtime client id
     */
    long getRuntimeClientId();

    /**
     * <code>fixed64 simulationId = 2;</code>.
     *
     * @return the simulation id
     */
    long getSimulationId();

    /**
     * <pre>
     * The client's friendly name
     * </pre>
     *
     * <code>string friendlyName = 3;</code>.
     *
     * @return the friendly name
     */
    java.lang.String getFriendlyName();

    /**
     * <pre>
     * The client's friendly name
     * </pre>
     *
     * <code>string friendlyName = 3;</code>.
     *
     * @return the friendly name bytes
     */
    com.google.protobuf.ByteString getFriendlyNameBytes();

    /**
     * <pre>
     * Flag indicating either a join or leave
     * </pre>
     *
     * <code>bool leave = 4;</code>.
     *
     * @return the leave
     */
    boolean getLeave();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return true, if successful
     */
    boolean hasTimestamp();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return the timestamp
     */
    com.google.protobuf.Timestamp getTimestamp();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return the timestamp or builder
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
  }

  /**
   * Protobuf type {@code JoinLeaveMessage}.
   */
  public static final class JoinLeaveMessage extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:JoinLeaveMessage)
      JoinLeaveMessageOrBuilder {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 0L;

    /**
     * Instantiates a new join leave message.
     *
     * @param builder the builder
     */
    // Use JoinLeaveMessage.newBuilder() to construct.
    private JoinLeaveMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    /**
     * Instantiates a new join leave message.
     */
    private JoinLeaveMessage() {
      runtimeClientId_ = 0L;
      simulationId_ = 0L;
      friendlyName_ = "";
      leave_ = false;
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#getUnknownFields()
     */
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    /**
     * Instantiates a new join leave message.
     *
     * @param input the input
     * @param extensionRegistry the extension registry
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    private JoinLeaveMessage(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              runtimeClientId_ = input.readFixed64();
              break;
            }
            case 17: {

              simulationId_ = input.readFixed64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              friendlyName_ = s;
              break;
            }
            case 32: {

              leave_ = input.readBool();
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ =
                  input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    /**
     * Gets the descriptor.
     *
     * @return the descriptor
     */
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return at.ac.ait.lablink.core.encoding.protobuf
          .LlJoinLeaveMessage.internal_static_JoinLeaveMessage_descriptor;
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#internalGetFieldAccessorTable()
     */
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage
          .internal_static_JoinLeaveMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              at.ac.ait.lablink.core.encoding.protobuf
                  .LlJoinLeaveMessage.JoinLeaveMessage.class,
              at.ac.ait.lablink.core.encoding.protobuf
                  .LlJoinLeaveMessage.JoinLeaveMessage.Builder.class
      );
    }

    /** The Constant RUNTIMECLIENTID_FIELD_NUMBER. */
    public static final int RUNTIMECLIENTID_FIELD_NUMBER = 1;

    /** The runtime client id. */
    private long runtimeClientId_;

    /**
     * <pre>
     * The client Id
     * </pre>
     *
     * <code>fixed64 runtimeClientId = 1;</code>.
     *
     * @return the runtime client id
     */
    public long getRuntimeClientId() {
      return runtimeClientId_;
    }

    /** The Constant SIMULATIONID_FIELD_NUMBER. */
    public static final int SIMULATIONID_FIELD_NUMBER = 2;

    /** The simulation id. */
    private long simulationId_;

    /**
     * <code>fixed64 simulationId = 2;</code>.
     *
     * @return the simulation id
     */
    public long getSimulationId() {
      return simulationId_;
    }

    /** The Constant FRIENDLYNAME_FIELD_NUMBER. */
    public static final int FRIENDLYNAME_FIELD_NUMBER = 3;

    /** The friendly name. */
    private volatile java.lang.Object friendlyName_;

    /**
     * <pre>
     * The client's friendly name
     * </pre>
     *
     * <code>string friendlyName = 3;</code>.
     *
     * @return the friendly name
     */
    public java.lang.String getFriendlyName() {
      java.lang.Object ref = friendlyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        friendlyName_ = s;
        return s;
      }
    }

    /**
     * <pre>
     * The client's friendly name
     * </pre>
     *
     * <code>string friendlyName = 3;</code>.
     *
     * @return the friendly name bytes
     */
    public com.google.protobuf.ByteString getFriendlyNameBytes() {
      java.lang.Object ref = friendlyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        friendlyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /** The Constant LEAVE_FIELD_NUMBER. */
    public static final int LEAVE_FIELD_NUMBER = 4;

    /** The leave. */
    private boolean leave_;

    /**
     * <pre>
     * Flag indicating either a join or leave
     * </pre>
     *
     * <code>bool leave = 4;</code>.
     *
     * @return the leave
     */
    public boolean getLeave() {
      return leave_;
    }

    /** The Constant TIMESTAMP_FIELD_NUMBER. */
    public static final int TIMESTAMP_FIELD_NUMBER = 5;

    /** The timestamp. */
    private com.google.protobuf.Timestamp timestamp_;

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return true, if successful
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return the timestamp
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return the timestamp or builder
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    /** The memoized is initialized. */
    private byte memoizedIsInitialized = -1;

    /**
     * @see com.google.protobuf.GeneratedMessageV3#isInitialized()
     */
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#writeTo(com.google.protobuf.CodedOutputStream)
     */
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (runtimeClientId_ != 0L) {
        output.writeFixed64(1, runtimeClientId_);
      }
      if (simulationId_ != 0L) {
        output.writeFixed64(2, simulationId_);
      }
      if (!getFriendlyNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, friendlyName_);
      }
      if (leave_ != false) {
        output.writeBool(4, leave_);
      }
      if (timestamp_ != null) {
        output.writeMessage(5, getTimestamp());
      }
      unknownFields.writeTo(output);
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#getSerializedSize()
     */
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }
      size = 0;
      if (runtimeClientId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeFixed64Size(1, runtimeClientId_);
      }
      if (simulationId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeFixed64Size(2, simulationId_);
      }
      if (!getFriendlyNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, friendlyName_);
      }
      if (leave_ != false) {
        size += com.google.protobuf.CodedOutputStream.computeBoolSize(4, leave_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, getTimestamp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    /**
     * @see com.google.protobuf.AbstractMessage#equals(java.lang.Object)
     */
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof at.ac.ait.lablink.core.encoding.protobuf
          .LlJoinLeaveMessage.JoinLeaveMessage)) {
        return super.equals(obj);
      }
      at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage other =
          (at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage) obj;

      boolean result = true;
      result = result && (getRuntimeClientId() == other.getRuntimeClientId());
      result = result && (getSimulationId() == other.getSimulationId());
      result = result && getFriendlyName().equals(other.getFriendlyName());
      result = result && (getLeave() == other.getLeave());
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && getTimestamp().equals(other.getTimestamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    /**
     * @see com.google.protobuf.AbstractMessage#hashCode()
     */
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RUNTIMECLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getRuntimeClientId());
      hash = (37 * hash) + SIMULATIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getSimulationId());
      hash = (37 * hash) + FRIENDLYNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFriendlyName().hashCode();
      hash = (37 * hash) + LEAVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getLeave());
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    /**
     * Parses the input data.
     *
     * @param data the data
     * @return join / leave message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseFrom(
          java.nio.ByteBuffer data
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    /**
     * Parses the input data.
     *
     * @param data the data
     * @param extensionRegistry the extension registry
     * @return join / leave message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseFrom(
          java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parses the input data.
     *
     * @param data the data
     * @return join / leave message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseFrom(
          com.google.protobuf.ByteString data
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    /**
     * Parses the input data.
     *
     * @param data the data
     * @param extensionRegistry the extension registry
     * @return join / leave message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parses the input data.
     *
     * @param data the data
     * @return join / leave message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseFrom(
          byte[] data
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    /**
     * Parses the input data.
     *
     * @param data the data
     * @param extensionRegistry the extension registry
     * @return join / leave message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseFrom(
          byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parses the input data.
     *
     * @param input the input
     * @return join / leave message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseFrom(
          java.io.InputStream input
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    /**
     * Parses the input data.
     *
     * @param input the input
     * @param extensionRegistry the extension registry
     * @return join / leave message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseFrom(
          java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    /**
     * Parses the input data.
     *
     * @param input the input
     * @return join / leave message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseFrom(
          com.google.protobuf.CodedInputStream input
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    /**
     * Parses the input data.
     *
     * @param input the input
     * @param extensionRegistry the extension registry
     * @return join / leave message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    /**
     * Parses delimited data.
     *
     * @param input the input
     * @return join / leave message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseDelimitedFrom(
          java.io.InputStream input
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    /**
     * Parses delimited data.
     *
     * @param input the input
     * @param extensionRegistry the extension registry
     * @return join / leave message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    /**
     * @see com.google.protobuf.MessageLite#newBuilderForType()
     */
    public Builder newBuilderForType() {
      return newBuilder();
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#newBuilderForType(
     * com.google.protobuf.GeneratedMessageV3.BuilderParent
     * )
     */
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * New builder.
     *
     * @return the builder
     */
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    /**
     * New builder.
     *
     * @param prototype the prototype
     * @return the builder
     */
    public static Builder newBuilder(
        at.ac.ait.lablink.core.encoding.protobuf
            .LlJoinLeaveMessage.JoinLeaveMessage prototype
    ) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * @see com.google.protobuf.MessageLite#toBuilder()
     */
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    /**
     * Protobuf type {@code JoinLeaveMessage}.
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JoinLeaveMessage)
        at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessageOrBuilder {

      /**
       * Gets the descriptor.
       *
       * @return the descriptor
       */
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return at.ac.ait.lablink.core.encoding.protobuf
            .LlJoinLeaveMessage.internal_static_JoinLeaveMessage_descriptor;
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#internalGetFieldAccessorTable()
       */
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage
            .internal_static_JoinLeaveMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                at.ac.ait.lablink.core.encoding.protobuf
                    .LlJoinLeaveMessage.JoinLeaveMessage.class,
                at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage
                    .JoinLeaveMessage.Builder.class
        );
      }

      /**
       * Instantiates a new builder.
       */
      // Construct using
      // at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      /**
       * Instantiates a new builder.
       *
       * @param parent the parent
       */
      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      /**
       * Maybe force builder initialization.
       */
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          return;
        }
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#clear()
       */
      public Builder clear() {
        super.clear();
        runtimeClientId_ = 0L;

        simulationId_ = 0L;

        friendlyName_ = "";

        leave_ = false;

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        return this;
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#getDescriptorForType()
       */
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return at.ac.ait.lablink.core.encoding.protobuf
            .LlJoinLeaveMessage.internal_static_JoinLeaveMessage_descriptor;
      }

      /**
       * @see com.google.protobuf.MessageLiteOrBuilder#getDefaultInstanceForType()
       */
      public at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
          getDefaultInstanceForType() {
        return at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
            .getDefaultInstance();
      }

      /**
       * @see com.google.protobuf.MessageLite.Builder#build()
       */
      public at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage build() {
        at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      /**
       * @see com.google.protobuf.MessageLite.Builder#buildPartial()
       */
      public at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
          buildPartial() {
        at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage result =
            new at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage(
                this
            );
        result.runtimeClientId_ = runtimeClientId_;
        result.simulationId_ = simulationId_;
        result.friendlyName_ = friendlyName_;
        result.leave_ = leave_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        onBuilt();
        return result;
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#clone()
       */
      public Builder clone() {
        return (Builder) super.clone();
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#setField(
       * com.google.protobuf.Descriptors.FieldDescriptor, java.lang.Object
       * )
       */
      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#clearField(
       * com.google.protobuf.Descriptors.FieldDescriptor
       * )
       */
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#clearOneof(
       * com.google.protobuf.Descriptors.OneofDescriptor
       * )
       */
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#setRepeatedField(
       * com.google.protobuf.Descriptors.FieldDescriptor, int, java.lang.Object
       * )
       */
      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#addRepeatedField(
       * com.google.protobuf.Descriptors.FieldDescriptor,
       * java.lang.Object
       * )
       */
      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      /**
       * @see com.google.protobuf.AbstractMessage.Builder#mergeFrom(com.google.protobuf.Message)
       */
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof at.ac.ait.lablink.core.encoding.protobuf
            .LlJoinLeaveMessage.JoinLeaveMessage) {
          return mergeFrom(
              (at.ac.ait.lablink.core.encoding.protobuf
                  .LlJoinLeaveMessage.JoinLeaveMessage) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      /**
       * Merge from.
       *
       * @param other the other
       * @return the builder
       */
      public Builder mergeFrom(
          at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage other) {
        if (other == at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
            .getDefaultInstance()) {
          return this;
        }
        if (other.getRuntimeClientId() != 0L) {
          setRuntimeClientId(other.getRuntimeClientId());
        }
        if (other.getSimulationId() != 0L) {
          setSimulationId(other.getSimulationId());
        }
        if (!other.getFriendlyName().isEmpty()) {
          friendlyName_ = other.friendlyName_;
          onChanged();
        }
        if (other.getLeave() != false) {
          setLeave(other.getLeave());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      /**
       * @see com.google.protobuf.AbstractMessage.Builder#mergeFrom(
       * com.google.protobuf.CodedInputStream,
       * com.google.protobuf.ExtensionRegistryLite
       * )
       */
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage
            .JoinLeaveMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage) e
                  .getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#isInitialized()
       */
      public final boolean isInitialized() {
        return true;
      }

      /** The runtime client id. */
      private long runtimeClientId_;

      /**
       * <pre>
       * The client Id
       * </pre>
       *
       * <code>fixed64 runtimeClientId = 1;</code>.
       *
       * @return the runtime client id
       */
      public long getRuntimeClientId() {
        return runtimeClientId_;
      }

      /**
       * <pre>
       * The client Id
       * </pre>
       *
       * <code>fixed64 runtimeClientId = 1;</code>.
       *
       * @param value the value
       * @return the builder
       */
      public Builder setRuntimeClientId(long value) {

        runtimeClientId_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * The client Id
       * </pre>
       *
       * <code>fixed64 runtimeClientId = 1;</code>.
       *
       * @return the builder
       */
      public Builder clearRuntimeClientId() {

        runtimeClientId_ = 0L;
        onChanged();
        return this;
      }

      /** The simulation id. */
      private long simulationId_;

      /**
       * <code>fixed64 simulationId = 2;</code>.
       *
       * @return the simulation id
       */
      public long getSimulationId() {
        return simulationId_;
      }

      /**
       * <code>fixed64 simulationId = 2;</code>.
       *
       * @param value the value
       * @return the builder
       */
      public Builder setSimulationId(long value) {

        simulationId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>fixed64 simulationId = 2;</code>.
       *
       * @return the builder
       */
      public Builder clearSimulationId() {

        simulationId_ = 0L;
        onChanged();
        return this;
      }

      /** The friendly name. */
      private java.lang.Object friendlyName_ = "";

      /**
       * <pre>
       * The client's friendly name
       * </pre>
       *
       * <code>string friendlyName = 3;</code>.
       *
       * @return the friendly name
       */
      public java.lang.String getFriendlyName() {
        java.lang.Object ref = friendlyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          friendlyName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <pre>
       * The client's friendly name
       * </pre>
       *
       * <code>string friendlyName = 3;</code>.
       *
       * @return the friendly name bytes
       */
      public com.google.protobuf.ByteString getFriendlyNameBytes() {
        java.lang.Object ref = friendlyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          friendlyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <pre>
       * The client's friendly name
       * </pre>
       *
       * <code>string friendlyName = 3;</code>.
       *
       * @param value the value
       * @return the builder
       */
      public Builder setFriendlyName(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        friendlyName_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * The client's friendly name
       * </pre>
       *
       * <code>string friendlyName = 3;</code>.
       *
       * @return the builder
       */
      public Builder clearFriendlyName() {

        friendlyName_ = getDefaultInstance().getFriendlyName();
        onChanged();
        return this;
      }

      /**
       * <pre>
       * The client's friendly name
       * </pre>
       *
       * <code>string friendlyName = 3;</code>.
       *
       * @param value the value
       * @return the builder
       */
      public Builder setFriendlyNameBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        friendlyName_ = value;
        onChanged();
        return this;
      }

      /** The leave. */
      private boolean leave_;

      /**
       * <pre>
       * Flag indicating either a join or leave
       * </pre>
       *
       * <code>bool leave = 4;</code>.
       *
       * @return the leave
       */
      public boolean getLeave() {
        return leave_;
      }

      /**
       * <pre>
       * Flag indicating either a join or leave
       * </pre>
       *
       * <code>bool leave = 4;</code>.
       *
       * @param value the value
       * @return the builder
       */
      public Builder setLeave(boolean value) {

        leave_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Flag indicating either a join or leave
       * </pre>
       *
       * <code>bool leave = 4;</code>.
       *
       * @return the builder
       */
      public Builder clearLeave() {

        leave_ = false;
        onChanged();
        return this;
      }

      /** The timestamp. */
      private com.google.protobuf.Timestamp timestamp_ = null;

      /** The timestamp builder. */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp,
          com.google.protobuf.Timestamp.Builder,
          com.google.protobuf.TimestampOrBuilder>
          timestampBuilder_;

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return true, if successful
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return the timestamp
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance()
              : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @param value the value
       * @return the builder
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @param builderForValue the builder for value
       * @return the builder
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @param value the value
       * @return the builder
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ = com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value)
                .buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return the builder
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return the timestamp builder
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {

        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return the timestamp or builder
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance()
              : timestamp_;
        }
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return the timestamp field builder
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp,
          com.google.protobuf.Timestamp.Builder,
          com.google.protobuf.TimestampOrBuilder>
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ =
              new com.google.protobuf.SingleFieldBuilderV3<
                  com.google.protobuf.Timestamp,
                  com.google.protobuf.Timestamp.Builder,
                  com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(), getParentForChildren(), isClean()
              );
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#setUnknownFields(
       * com.google.protobuf.UnknownFieldSet
       * )
       */
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#mergeUnknownFields(
       * com.google.protobuf.UnknownFieldSet
       * )
       */
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:JoinLeaveMessage)
    }

    /** The Constant DEFAULT_INSTANCE. */
    // @@protoc_insertion_point(class_scope:JoinLeaveMessage)
    private static final at.ac.ait.lablink.core.encoding.protobuf
        .LlJoinLeaveMessage.JoinLeaveMessage DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE =
          new at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage();
    }

    /**
     * Gets the default instance.
     *
     * @return the default instance
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    /** The Constant PARSER. */
    private static final com.google.protobuf.Parser<JoinLeaveMessage> PARSER =
        new com.google.protobuf.AbstractParser<JoinLeaveMessage>() {
          public JoinLeaveMessage parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new JoinLeaveMessage(input, extensionRegistry);
          }
        };

    /**
     * Parser.
     *
     * @return the com.google.protobuf. parser
     */
    public static com.google.protobuf.Parser<JoinLeaveMessage> parser() {
      return PARSER;
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#getParserForType()
     */
    @java.lang.Override
    public com.google.protobuf.Parser<JoinLeaveMessage> getParserForType() {
      return PARSER;
    }

    /**
     * @see com.google.protobuf.MessageLiteOrBuilder#getDefaultInstanceForType()
     */
    public at.ac.ait.lablink.core.encoding.protobuf.LlJoinLeaveMessage.JoinLeaveMessage
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /** The Constant internal_static_JoinLeaveMessage_descriptor. */
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_JoinLeaveMessage_descriptor;

  /** The Constant internal_static_JoinLeaveMessage_fieldAccessorTable. */
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JoinLeaveMessage_fieldAccessorTable;

  /**
   * Gets the descriptor.
   *
   * @return the descriptor
   */
  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  /** The descriptor. */
  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {"\n\026JoinLeaveMessage.proto\032\037google/protobu"
        + "f/timestamp.proto\"\225\001\n\020JoinLeaveMessage\022\027"
        + "\n\017runtimeClientId\030\001 \001(\006\022\024\n\014simulationId\030"
        + "\002 \001(\006\022\024\n\014friendlyName\030\003 \001(\t\022\r\n\005leave\030\004 \001"
        + "(\010\022-\n\ttimestamp\030\005 \001(\0132\032.google.protobuf."
        + "TimestampB@\n*at.ac.ait.lablink.core.en"
        + "coding.protobufB\022LlJoinLeaveMessageb\006pro" + "to3"};
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
            com.google.protobuf.TimestampProto.getDescriptor(),},
        assigner);
    internal_static_JoinLeaveMessage_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_JoinLeaveMessage_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_JoinLeaveMessage_descriptor, new java.lang.String[] {"RuntimeClientId",
                "SimulationId", "FriendlyName", "Leave", "Timestamp",});
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
