//
// Copyright (c) AIT Austrian Institute of Technology GmbH.
// Distributed under the terms of the Modified BSD License.
//

package at.ac.ait.lablink.core.encoding.protobuf;

import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;

/**
 * Class LlSyncInviteMessage.
 *
 * <p>This file has been generated by the protocol buffer compiler. It has
 * been slightly modified to comply with (most of) the style checker rules
 * and generate valid Javadoc output.
 *
 * <p>Only edit this file if you really know what you are doing!!!
 */
public final class LlSyncInviteMessage {

  /**
   * Instantiates a new Lablink invite message.
   */
  private LlSyncInviteMessage() {}

  /**
   * Register all extensions.
   *
   * @param registry the registry
   */
  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  /**
   * Register all extensions.
   *
   * @param registry the registry
   */
  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  /**
   * The Interface SyncInviteMessageOrBuilder.
   */
  public interface SyncInviteMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SyncInviteMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>fixed64 simulationId = 1;</code>.
     *
     * @return the simulation id
     */
    long getSimulationId();

    /**
     * <code>double timestep = 2;</code>.
     *
     * @return the timestep
     */
    double getTimestep();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return true, if successful
     */
    boolean hasTimestamp();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return the timestamp
     */
    com.google.protobuf.Timestamp getTimestamp();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return the timestamp or builder
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
  }

  /**
   * Protobuf type {@code SyncInviteMessage}.
   */
  public static final class SyncInviteMessage extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:SyncInviteMessage)
      SyncInviteMessageOrBuilder {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 0L;

    /**
     * Instantiates a new Parses the data..
     *
     * @param builder the builder
     */
    // Use SyncInviteMessage.newBuilder() to construct.
    private SyncInviteMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    /**
     * Instantiates a new Parses the data..
     */
    private SyncInviteMessage() {
      simulationId_ = 0L;
      timestep_ = 0D;
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#getUnknownFields()
     */
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    /**
     * Instantiates a new Parses the data..
     *
     * @param input the input
     * @param extensionRegistry the extension registry
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    private SyncInviteMessage(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              simulationId_ = input.readFixed64();
              break;
            }
            case 17: {

              timestep_ = input.readDouble();
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ =
                  input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    /**
     * Gets the descriptor.
     *
     * @return the descriptor
     */
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return at.ac.ait.lablink.core.encoding.protobuf
          .LlSyncInviteMessage.internal_static_SyncInviteMessage_descriptor;
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#internalGetFieldAccessorTable()
     */
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage
          .internal_static_SyncInviteMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              at.ac.ait.lablink.core.encoding.protobuf
                  .LlSyncInviteMessage.SyncInviteMessage.class,
              at.ac.ait.lablink.core.encoding.protobuf
                  .LlSyncInviteMessage.SyncInviteMessage.Builder.class
      );
    }

    /** The Constant SIMULATIONID_FIELD_NUMBER. */
    public static final int SIMULATIONID_FIELD_NUMBER = 1;

    /** The simulation id. */
    private long simulationId_;

    /**
     * <code>fixed64 simulationId = 1;</code>.
     *
     * @return the simulation id
     */
    public long getSimulationId() {
      return simulationId_;
    }

    /** The Constant TIMESTEP_FIELD_NUMBER. */
    public static final int TIMESTEP_FIELD_NUMBER = 2;

    /** The timestep. */
    private double timestep_;

    /**
     * <code>double timestep = 2;</code>.
     *
     * @return the timestep
     */
    public double getTimestep() {
      return timestep_;
    }

    /** The Constant TIMESTAMP_FIELD_NUMBER. */
    public static final int TIMESTAMP_FIELD_NUMBER = 5;

    /** The timestamp. */
    private com.google.protobuf.Timestamp timestamp_;

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return true, if successful
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return the timestamp
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     *
     * @return the timestamp or builder
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    /** The memoized is initialized. */
    private byte memoizedIsInitialized = -1;

    /**
     * @see com.google.protobuf.GeneratedMessageV3#isInitialized()
     */
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#writeTo(com.google.protobuf.CodedOutputStream)
     */
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (simulationId_ != 0L) {
        output.writeFixed64(1, simulationId_);
      }
      if (timestep_ != 0D) {
        output.writeDouble(2, timestep_);
      }
      if (timestamp_ != null) {
        output.writeMessage(5, getTimestamp());
      }
      unknownFields.writeTo(output);
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#getSerializedSize()
     */
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }
      size = 0;
      if (simulationId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeFixed64Size(1, simulationId_);
      }
      if (timestep_ != 0D) {
        size += com.google.protobuf.CodedOutputStream.computeDoubleSize(2, timestep_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, getTimestamp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    /**
     * @see com.google.protobuf.AbstractMessage#equals(java.lang.Object)
     */
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof at.ac.ait.lablink.core.encoding.protobuf
          .LlSyncInviteMessage.SyncInviteMessage)) {
        return super.equals(obj);
      }
      at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage other =
          (at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage) obj;

      boolean result = true;
      result = result && (getSimulationId() == other.getSimulationId());
      result = result && (java.lang.Double.doubleToLongBits(getTimestep()) == java.lang.Double
          .doubleToLongBits(other.getTimestep()));
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && getTimestamp().equals(other.getTimestamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    /**
     * @see com.google.protobuf.AbstractMessage#hashCode()
     */
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIMULATIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getSimulationId());
      hash = (37 * hash) + TIMESTEP_FIELD_NUMBER;
      hash = (53 * hash)
          + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getTimestep()));
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    /**
     * Parses the data.
     *
     * @param data the data
     * @return sync invite message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseFrom(
          java.nio.ByteBuffer data
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    /**
     * Parses the data.
     *
     * @param data the data
     * @param extensionRegistry the extension registry
     * @return sync invite message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parses the data.
     *
     * @param data the data
     * @return sync invite message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseFrom(
          com.google.protobuf.ByteString data
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    /**
     * Parses the data.
     *
     * @param data the data
     * @param extensionRegistry the extension registry
     * @return sync invite message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parses the data.
     *
     * @param data the data
     * @return sync invite message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseFrom(
          byte[] data
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    /**
     * Parses the data.
     *
     * @param data the data
     * @param extensionRegistry the extension registry
     * @return sync invite message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parses the data.
     *
     * @param input the input
     * @return sync invite message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseFrom(
          java.io.InputStream input
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    /**
     * Parses the data.
     *
     * @param input the input
     * @param extensionRegistry the extension registry
     * @return sync invite message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    /**
     * Parses the data.
     *
     * @param input the input
     * @return sync invite message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseFrom(
          com.google.protobuf.CodedInputStream input
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    /**
     * Parses the data.
     *
     * @param input the input
     * @param extensionRegistry the extension registry
     * @return sync invite message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    /**
     * Parses delimited data.
     *
     * @param input the input
     * @return sync invite message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseDelimitedFrom(
          java.io.InputStream input
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    /**
     * Parses delimited data.
     *
     * @param input the input
     * @param extensionRegistry the extension registry
     * @return sync invite message
     * @throws IOException Signals that an I/O exception has occurred.
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    /**
     * @see com.google.protobuf.MessageLite#newBuilderForType()
     */
    public Builder newBuilderForType() {
      return newBuilder();
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#newBuilderForType(
     * com.google.protobuf.GeneratedMessageV3.BuilderParent
     * )
     */
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent
    ) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * New builder.
     *
     * @return the builder
     */
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    /**
     * New builder.
     *
     * @param prototype the prototype
     * @return the builder
     */
    public static Builder newBuilder(
        at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage prototype
    ) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * @see com.google.protobuf.MessageLite#toBuilder()
     */
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    /**
     * Protobuf type {@code SyncInviteMessage}.
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SyncInviteMessage)
        at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessageOrBuilder {

      /**
       * Gets the descriptor.
       *
       * @return the descriptor
       */
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return at.ac.ait.lablink.core.encoding.protobuf
            .LlSyncInviteMessage.internal_static_SyncInviteMessage_descriptor;
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#internalGetFieldAccessorTable()
       */
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage
            .internal_static_SyncInviteMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                at.ac.ait.lablink.core.encoding.protobuf
                    .LlSyncInviteMessage.SyncInviteMessage.class,
                at.ac.ait.lablink.core.encoding.protobuf
                    .LlSyncInviteMessage.SyncInviteMessage.Builder.class
        );
      }

      /**
       * Instantiates a new builder.
       */
      // Construct using
      // at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      /**
       * Instantiates a new builder.
       *
       * @param parent the parent
       */
      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      /**
       * Maybe force builder initialization.
       */
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          return;
        }
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#clear()
       */
      public Builder clear() {
        super.clear();
        simulationId_ = 0L;

        timestep_ = 0D;

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        return this;
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#getDescriptorForType()
       */
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return at.ac.ait.lablink.core.encoding.protobuf
            .LlSyncInviteMessage.internal_static_SyncInviteMessage_descriptor;
      }

      /**
       * @see com.google.protobuf.MessageLiteOrBuilder#getDefaultInstanceForType()
       */
      public at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
          getDefaultInstanceForType() {
        return at.ac.ait.lablink.core.encoding.protobuf
            .LlSyncInviteMessage.SyncInviteMessage.getDefaultInstance();
      }

      /**
       * @see com.google.protobuf.MessageLite.Builder#build()
       */
      public at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
          build() {
        at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      /**
       * @see com.google.protobuf.MessageLite.Builder#buildPartial()
       */
      public at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
          buildPartial() {
        at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage result =
            new at.ac.ait.lablink.core.encoding.protobuf
                .LlSyncInviteMessage.SyncInviteMessage(this);
        result.simulationId_ = simulationId_;
        result.timestep_ = timestep_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        onBuilt();
        return result;
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#clone()
       */
      public Builder clone() {
        return (Builder) super.clone();
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#setField(
       * com.google.protobuf.Descriptors.FieldDescriptor, java.lang.Object
       * )
       */
      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#clearField(
       * com.google.protobuf.Descriptors.FieldDescriptor
       * )
       */
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#clearOneof(
       * com.google.protobuf.Descriptors.OneofDescriptor
       * )
       */
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#setRepeatedField(
       * com.google.protobuf.Descriptors.FieldDescriptor, int, java.lang.Object)
       */
      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#addRepeatedField(
       * com.google.protobuf.Descriptors.FieldDescriptor, java.lang.Object
       * )
       */
      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      /**
       * @see com.google.protobuf.AbstractMessage.Builder#mergeFrom(com.google.protobuf.Message)
       */
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof at.ac.ait.lablink.core.encoding.protobuf
            .LlSyncInviteMessage.SyncInviteMessage) {
          return mergeFrom(
              (at.ac.ait.lablink.core.encoding.protobuf
                  .LlSyncInviteMessage.SyncInviteMessage) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      /**
       * Merge from.
       *
       * @param other the other
       * @return the builder
       */
      public Builder mergeFrom(
          at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage other) {
        if (other == at.ac.ait.lablink.core.encoding.protobuf
            .LlSyncInviteMessage.SyncInviteMessage.getDefaultInstance()) {
          return this;
        }
        if (other.getSimulationId() != 0L) {
          setSimulationId(other.getSimulationId());
        }
        if (other.getTimestep() != 0D) {
          setTimestep(other.getTimestep());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      /**
       * @see com.google.protobuf.AbstractMessage.Builder#mergeFrom(
       * com.google.protobuf.CodedInputStream,
       * com.google.protobuf.ExtensionRegistryLite
       * )
       */
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry
      ) throws java.io.IOException {
        at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
            parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage) e
                  .getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#isInitialized()
       */
      public final boolean isInitialized() {
        return true;
      }

      /** The simulation id. */
      private long simulationId_;

      /**
       * <code>fixed64 simulationId = 1;</code>.
       *
       * @return the simulation id
       */
      public long getSimulationId() {
        return simulationId_;
      }

      /**
       * <code>fixed64 simulationId = 1;</code>.
       *
       * @param value the value
       * @return the builder
       */
      public Builder setSimulationId(long value) {

        simulationId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>fixed64 simulationId = 1;</code>.
       *
       * @return the builder
       */
      public Builder clearSimulationId() {

        simulationId_ = 0L;
        onChanged();
        return this;
      }

      /** The timestep. */
      private double timestep_;

      /**
       * <code>double timestep = 2;</code>.
       *
       * @return the timestep
       */
      public double getTimestep() {
        return timestep_;
      }

      /**
       * <code>double timestep = 2;</code>.
       *
       * @param value the value
       * @return the builder
       */
      public Builder setTimestep(double value) {

        timestep_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>double timestep = 2;</code>.
       *
       * @return the builder
       */
      public Builder clearTimestep() {

        timestep_ = 0D;
        onChanged();
        return this;
      }

      /** The timestamp. */
      private com.google.protobuf.Timestamp timestamp_ = null;

      /** The timestamp builder. */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp,
          com.google.protobuf.Timestamp.Builder,
          com.google.protobuf.TimestampOrBuilder> timestampBuilder_;

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return true, if successful
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return the timestamp
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance()
              : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @param value the value
       * @return the builder
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @param builderForValue the builder for value
       * @return the builder
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @param value the value
       * @return the builder
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ = com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value)
                .buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return the builder
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return the timestamp builder
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {

        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return the timestamp or builder
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance()
              : timestamp_;
        }
      }

      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       *
       * @return the timestamp field builder
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp,
          com.google.protobuf.Timestamp.Builder,
          com.google.protobuf.TimestampOrBuilder> getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ =
              new com.google.protobuf.SingleFieldBuilderV3<
                  com.google.protobuf.Timestamp,
                  com.google.protobuf.Timestamp.Builder,
                  com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(), getParentForChildren(), isClean()
              );
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#setUnknownFields(com.google.protobuf.
       * UnknownFieldSet)
       */
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      /**
       * @see com.google.protobuf.GeneratedMessageV3.Builder#mergeUnknownFields(com.google.protobuf.
       * UnknownFieldSet)
       */
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:SyncInviteMessage)
    }

    /** The Constant DEFAULT_INSTANCE. */
    // @@protoc_insertion_point(class_scope:SyncInviteMessage)
    private static final at.ac.ait.lablink.core.encoding.protobuf
        .LlSyncInviteMessage.SyncInviteMessage DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE =
          new at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage();
    }

    /**
     * Gets the default instance.
     *
     * @return the default instance
     */
    public static at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    /** The Constant PARSER. */
    private static final com.google.protobuf.Parser<SyncInviteMessage> PARSER =
        new com.google.protobuf.AbstractParser<SyncInviteMessage>() {
          public SyncInviteMessage parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry
          ) throws com.google.protobuf.InvalidProtocolBufferException {
            return new SyncInviteMessage(input, extensionRegistry);
          }
    };

    /**
     * Parser.
     *
     * @return the com.google.protobuf. parser
     */
    public static com.google.protobuf.Parser<SyncInviteMessage> parser() {
      return PARSER;
    }

    /**
     * @see com.google.protobuf.GeneratedMessageV3#getParserForType()
     */
    @java.lang.Override
    public com.google.protobuf.Parser<SyncInviteMessage> getParserForType() {
      return PARSER;
    }

    /**
     * @see com.google.protobuf.MessageLiteOrBuilder#getDefaultInstanceForType()
     */
    public at.ac.ait.lablink.core.encoding.protobuf.LlSyncInviteMessage.SyncInviteMessage
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /** The Constant internal_static_SyncInviteMessage_descriptor. */
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_SyncInviteMessage_descriptor;

  /** The Constant internal_static_SyncInviteMessage_fieldAccessorTable. */
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SyncInviteMessage_fieldAccessorTable;

  /**
   * Gets the descriptor.
   *
   * @return the descriptor
   */
  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  /** The descriptor. */
  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {"\n\027SyncInviteMessage.proto\032\037google/protob"
        + "uf/timestamp.proto\"j\n\021SyncInviteMessage\022"
        + "\024\n\014simulationId\030\001 \001(\006\022\020\n\010timestep\030\002 \001(\001\022"
        + "-\n\ttimestamp\030\005 \001(\0132\032.google.protobuf.Tim"
        + "estampBA\n*at.ac.ait.lablink.core.encod"
        + "ing.protobufB\023LlSyncInviteMessageb\006proto" + "3"};
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
            com.google.protobuf.TimestampProto.getDescriptor(),},
        assigner);
    internal_static_SyncInviteMessage_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_SyncInviteMessage_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_SyncInviteMessage_descriptor,
            new java.lang.String[] {"SimulationId", "Timestep", "Timestamp",});
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
